apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketing-automation

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: marketing-automation-suite/n8n-orchestration
    newTag: latest

