apiVersion: v1
kind: Service
metadata:
  name: xlam-server
  namespace: marketing-automation
spec:
  selector:
    app: xlam-server
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

