apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketing-automation

resources:
  - deployment.yaml
  - configmap.yaml

images:
  - name: marketing-automation-suite/nft-software-engine
    newTag: latest

