apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketing-automation

resources:
  - ../../base
  - ../../services/xlam-server
  - ../../services/n8n
  - ../../services/crm-twenty
  - ../../services/dashboard-streamlit
  - ../../infrastructure/postgresql
  - ../../infrastructure/redis

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

